### ISSUE TITLE
Cassandra requires authentication

### ISSUE THREAD

**Issue by tungtt1006** [thatdot/quine#26]
**Describe the bug**
Hi, my Cassandra DB (Helm bitnami/cassandra) requires authentication with username, password. How can I configure it in quine.conf ? Thanks.
- I got this error:
`Authentication error on node cassandra/<unresolved>:9042: Node cassandra/<unresolved>:9042 requires authentication (org.apache.cassandra.auth.PasswordAuthenticator), but no authenticator configured`

**Comment by maglietti** [comment]
Hi @tungtt1006,

Quine uses the [DataStax Java Driver for Apache Cassandra](https://mvnrepository.com/artifact/com.datastax.oss/java-driver-core/4.15.0) for connections. You can configure authentication by adding `datastax-java-driver` configuration to your local `quine.conf` file as described on the [Authentication page](https://docs.datastax.com/en/developer/java-driver/4.14/manual/core/authentication/).

For example, adding the following into a `quine.conf` file will set up basic authentication. 

``` json
quine.store {
  # Store data in a local Bitnami Apache Cassandra instance
  type = cassandra
}
datastax-java-driver {
  advanced {
    auth-provider {
      class = PlainTextAuthProvider
      username = cassandra
      password = cassandra
    }
  }
}
```

Then launch Quine with the following command line:

```shell
java -Dconfig.file=quine.conf -jar quine.jar
```
