### ISSUE TITLE
Will quine merge to pekko or keep using Akka 2.6.x?

### ISSUE THREAD

**Issue by He-Pin** [thatdot/quine#32]
I think this project is very intreasting but never managed to read all the code:)

Will quine merge to pekko or stay with Akka 2.6.21?

**Comment by brackishman** [comment]
Hi He-Pin, thanks for asking!

We are monitoring the progress of Pekko very closely. Currently the Pekko ecosystem is not yet ready for production for us. We have dependencies which are dependent on Akka, and those dependencies do not yet have Pekko support. We’re also watching Lightbend closely to see how they navigate this situation. We’ll stay with Akka for now, but if/when the Pekko ecosystem is ready, we will give it serious consideration.

**Comment by He-Pin** [comment]
Thanks for the update, yes, lightbend provides great supports.

**Comment by He-Pin** [comment]
@brackishman The 1.0.0 release of connectors is on the way, see https://github.com/apache/incubator-pekko-connectors/pull/229 .

cc @pjfanning

**Comment by mdedetrich** [comment]
> We are monitoring the progress of Pekko very closely. Currently the Pekko ecosystem is not yet ready for production for us. We have dependencies which are dependent on Akka, and those dependencies do not yet have Pekko support. We’re also watching Lightbend closely to see how they navigate this situation. We’ll stay with Akka for now, but if/when the Pekko ecosystem is ready, we will give it serious consideration.

Can you let us know which of these dependencies that you depend on which are still relying on Akka? We are doing our best to help the Akka library ecosystem to support Pekko as well.

**Comment by pjfanning** [comment]
I had a quick look and after pekko connectors (alpakka equivalent) is released then there are 2 more 3rd party libs that are needed by quine.
* https://github.com/StreetContxt/kcl-akka-stream/issues
* https://github.com/endpoints4s/endpoints4s/issues/1103

**Comment by brackishman** [comment]
@mdedetrich, @pjfanning is correct in their assessment. We are watching for when we can build with fully released versions of pekko including pekko connectors, and when we have a path forward with these dependencies. The 1 year support period from Lightbend on Akka 2.6 unfortunately ends in September, so we're very much interested in pekko when it make sense.

**Comment by brackishman** [comment]
@pjfanning , The documentation for several pekko connectors (i.e. S3, Kinesis, and File) all indicate they are published to maven, but when I search maven I'm not seeing them. Is the documentation ahead of the actual release?

**Comment by mdedetrich** [comment]
> Is the documentation ahead of the actual release?

Yes, however do note we publish artifacts nightly to Apache Snapshots repo, i.e. `https://repository.apache.org/content/repositories/snapshots/`.

Since it appears you are using sbt you can just do the following

```sbt
ThisBuild / resolvers += Resolver.ApacheMavenSnapshotsRepo
```

to add the resolvers and navigate https://repository.apache.org/content/groups/snapshots/org/apache/pekko/ to find the latest version of the artifact you are interested in

**Comment by pjfanning** [comment]
@brackishman there isn't much point in quine being too proactive. You have a number of dependencies that are not ready for Pekko. See https://github.com/thatdot/quine/issues/32#issuecomment-1685969632

**Comment by pjfanning** [comment]
@brackishman I've opened a discussion about doing a Pekko Connectors 1.0.0 release. https://lists.apache.org/thread/gd4mhjf5zfd4gcdzcv92jsfy5hnv2ggg

**Comment by brackishman** [comment]
Thanks to the pekko community, all obstacles have been removed which prevented us from switching to pekko. As a result, we are in the process of switching now. More to come in the next could of weeks.
